repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.4.0
  hooks:
  - id: trailing-whitespace
    exclude: .gitignore
  - id: end-of-file-fixer
  - id: check-added-large-files
- repo: https://github.com/codespell-project/codespell
  rev: v2.0.0
  hooks:
  - id: codespell
    args:
    - --quiet-level=2
    - --check-filenames
    - --check-hidden
- repo: https://github.com/adrienverge/yamllint.git
  rev: v1.26.0
  hooks:
  - id: yamllint
- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks.git
  rev: v2.0.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix, --indent, '2']
- repo: https://github.com/igorshubovych/markdownlint-cli
  rev: v0.26.0
  hooks:
  - id: markdownlint
- repo: https://github.com/Vimjas/vint
  rev: v0.4a3
  hooks:
  - id: vint
